name: Dev Build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Get Build Version
        run: echo bv=`echo "${{ GITHUB.SHA }}" | cut -b 1-8` >> "$GITHUB_ENV"
      - name: Build with Maven
        run: mvn compile package -f pom.xml
      - name: Upload to Actions
        uses: actions/upload-artifact@v4.3.0
        with:
          name: "BDR-DEV-build-${{ env.bv }}"
          path: "target/*.jar"
